name: CxONE Dast Scan Security Tweets
on:
  #pull_request:
  # branches:
  # - main
  #push: 
  # branches:
  # - main
    
  workflow_dispatch: #adds a 'run now' button
  
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif
     # The type of runner that the job will run on 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Reclaim output directory
        if: always()
        run: sudo chown -R 1001:1001 ${{ github.workspace }}/output
      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v1.0.4
        env:
          CX_APIKEY: ${{ secrets.CX_ONE_API_KEY }}
        with:
            command: web
            config: './security_tweets_dast_scan.yaml'
            environment_id: "a8e3127b-5270-46d9-90ba-33aad42b0f1b"
            log_level: info
            base_url: "https://deu.ast.checkmarx.net/"
            fail_on: ""
            verbose: true
            output: ./output
      - uses: actions/upload-artifact@v3
        if: always()
        name: Upload Logs
        with:
          name: report
          path: ./output
          
